typography_spectrum: 0.9397681383416057
color:
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
  brandStrength: 0.8125
  lightness: 0.6493136321660131
  saturation: 0.625
  rhythmicContrast: 0.9939850475639105
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.27044311561621726
analytics:
  google: null
  facebook: null
  twitter: null
name: 360°
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: Virtualni sprehodi 360°
    id: 582ef161-d623-4fc2-9fb2-f9b804d6b74a
    type: content
  - name: Cenik Izdelave
    id: 648f705b-7b7d-4324-8452-42a9c8d1e4be
    type: content
  - name: Kontakt
    id: a784ed54-4052-4af4-bb23-170084e3b4fd
    type: content
favicon: null
title: 360° VR toure
description: 'cerdobeer mobi: 0310310301 Lendavske gorice132 gmail:cerdobeer@gmail.com'
purpose: []
